version: "3.4"
services:
  mq:
    container_name: python_mq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  anti_spam:
    build: "anti_spam_core"
    depends_on:
      - mq
